# 최종 추천 environment.yml
name: pyopengl
channels:
  - pytorch   # PyTorch 공식 채널을 최우선으로
  - defaults  # 기본 채널
  - conda-forge # 추가적인 패키지를 위한 채널
dependencies:
  # 1. 핵심 과학 패키지 (Conda가 관리하도록 함)
  - python=3.12   # 세부 버전은 Conda가 알아서 맞추도록 함
  - pytorch
  - torchvision
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  
  # 2. 기타 유틸리티 (Conda로 설치)
  - bzip2
  - openssl
  - pip
  - sqlite
  - tqdm
  - yaml
  - setuptools
  - wheel
  - xz
  - zlib

  # 3. Conda 채널에 없는 경우에만 Pip 사용
  - pip:
      - accelerate
      - denoising-diffusion-pytorch
      - einops
      - ema-pytorch
      - glfw
      - huggingface-hub
      - imgui
      - pymo
      - pyopengl
      - pyopengl-accelerate
      - pygame
      - pytorch-fid
      - safetensors